# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import techlinx.Blog.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la categoria', max_length=150)),
                ('slug', models.SlugField(help_text='Slug de url del post', max_length=200, unique=True)),
                ('imagen', models.ImageField(help_text='Imagen de la categoria', upload_to=techlinx.Blog.models.path_save_images)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(help_text='Titulo del Post', max_length=150)),
                ('slug', models.SlugField(help_text='Slug de url del post', max_length=200, unique=True)),
                ('contenido', models.TextField(help_text='Contenido del Post')),
                ('cover', models.ImageField(help_text='Imagen de cover del post', upload_to=techlinx.Blog.models.path_save_images)),
                ('publicado', models.BooleanField(default=False, help_text='Check si post esta publicado', verbose_name='¿Post publicado?')),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha en que se creo el post')),
                ('fecha_publicacion', models.DateField(blank=True, help_text='Fecha en la que se publico el post', null=True)),
                ('tiempo_estimado', models.IntegerField(default=0, help_text='Tiempo aproximado de lectura del post')),
                ('autor', models.ForeignKey(help_text='Usuario Autor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='Staff.Staff')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoria del post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='Blog.Categories')),
            ],
        ),
    ]
