# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-29 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=160),
        ),
    ]
